/**
 * Works out which exercise media objects actually exist, and writes
 * `src/data/exerciseMediaManifest.ts`.
 *
 *   npm run seo:resolve-exercise-media
 *
 * Needs `VITE_SUPABASE_URL` and network access to the Storage bucket, so it is
 * run by hand and its output committed. The static content pages then read the
 * committed file, which keeps CI and Vercel builds offline and deterministic.
 *
 * The library stores photo paths by convention and the app retries `.png` and
 * `.jpg` in the browser when the guess is wrong. A static page cannot retry, so
 * this probes each candidate and records the one that is really there — plus its
 * intrinsic dimensions, so the page can reserve space and avoid layout shift.
 *
 * Re-run it whenever media is uploaded or replaced, and commit the diff.
 */
import { writeFile } from 'node:fs/promises';
import sharp from 'sharp';
import { EXERCISE_LIBRARY } from '../src/data/exerciseLibrary';
import { getExerciseImagePathCandidates } from '../src/lib/media/getExerciseMediaUrl';
import { buildMediaAlt, buildPublicMediaUrl } from '../src/lib/media/exerciseMediaManifest';
import type { ExerciseMediaEntry } from '../src/data/exerciseMediaManifest';

const OUTPUT = 'src/data/exerciseMediaManifest.ts';

async function main(): Promise<void> {
  const baseUrl = process.env.VITE_SUPABASE_URL?.trim();
  if (!baseUrl) {
    console.error('VITE_SUPABASE_URL is not set. Cannot reach the exercise-media bucket.');
    process.exitCode = 1;
    return;
  }

  const entries: Array<[string, ExerciseMediaEntry]> = [];
  const missing: string[] = [];

  for (const exercise of EXERCISE_LIBRARY) {
    const photo = exercise.photos[0];
    if (!photo?.url?.trim()) {
      missing.push(`${exercise.id} (no photo path in the library)`);
      continue;
    }

    const resolved = await resolveFirstExisting(baseUrl, photo.url);
    if (!resolved) {
      missing.push(`${exercise.id} (no object at any candidate extension)`);
      continue;
    }

    entries.push([
      exercise.id,
      {
        path: resolved.path,
        width: resolved.width,
        height: resolved.height,
        alt: buildMediaAlt(exercise.name, photo.caption),
      },
    ]);
  }

  await writeFile(OUTPUT, renderManifest(entries), 'utf8');

  console.log(`Resolved ${entries.length} of ${EXERCISE_LIBRARY.length} exercise images.`);
  if (missing.length > 0) {
    console.log(`\nNo image for ${missing.length}:`);
    for (const line of missing) {
      console.log(`  ${line}`);
    }
    console.log('\nThese render no image, which is intended — upload the media and re-run.');
  }
  console.log(`\nWrote ${OUTPUT}. Commit it.`);
}

interface ResolvedObject {
  path: string;
  width: number;
  height: number;
}

/**
 * Downloads rather than HEADs: the dimensions are the point, and a HEAD would
 * only tell us the object exists. These are small stills and this runs by hand.
 */
async function resolveFirstExisting(
  baseUrl: string,
  relativePath: string
): Promise<ResolvedObject | null> {
  for (const candidate of getExerciseImagePathCandidates(relativePath)) {
    const url = buildPublicMediaUrl(baseUrl, candidate);
    if (!url) {
      continue;
    }
    try {
      const response = await fetch(url);
      if (!response.ok) {
        continue;
      }
      const buffer = Buffer.from(await response.arrayBuffer());
      const { width, height } = await sharp(buffer).metadata();
      if (!width || !height) {
        console.warn(`  ${candidate}: readable object but no dimensions; skipping.`);
        continue;
      }
      return { path: candidate, width, height };
    } catch (error) {
      console.warn(`  ${candidate}: ${(error as Error).message}`);
    }
  }
  return null;
}

function renderManifest(entries: Array<[string, ExerciseMediaEntry]>): string {
  const body = entries
    .map(
      ([id, entry]) =>
        `  '${id}': {\n` +
        `    path: ${JSON.stringify(entry.path)},\n` +
        `    width: ${entry.width},\n` +
        `    height: ${entry.height},\n` +
        `    alt: ${JSON.stringify(entry.alt)},\n` +
        `  },`
    )
    .join('\n');

  return `/**
 * Which exercise media objects actually exist, resolved once and committed.
 *
 * GENERATED by scripts/resolve-exercise-media.ts — do not edit by hand.
 * Re-run \`npm run seo:resolve-exercise-media\` after uploading or replacing
 * media, and commit the diff.
 *
 * The library stores photo paths by convention (\`{id}/sequence.jpeg\`), and the
 * app copes with a wrong guess by retrying \`.png\` and \`.jpg\` in the browser. A
 * static page cannot retry, so this map records the path that is really there.
 *
 * An exercise absent from this map renders no image. That is deliberate — a
 * missing entry is a missing object, and no image beats a broken one.
 */
export interface ExerciseMediaEntry {
  /** Path inside the \`exercise-media\` bucket, with the extension that exists. */
  path: string;
  /** Intrinsic pixel dimensions, so the page can reserve space and avoid layout shift. */
  width: number;
  height: number;
  /** Never empty: these images carry instructional content. */
  alt: string;
}

export const EXERCISE_MEDIA_MANIFEST: Record<string, ExerciseMediaEntry> = {
${body}
};
`;
}

void main();
