/**
 * Which exercise media objects actually exist, resolved once and committed.
 *
 * GENERATED by scripts/resolve-exercise-media.ts — do not edit by hand.
 * Re-run `npm run seo:resolve-exercise-media` after uploading or replacing
 * media, and commit the diff.
 *
 * The library stores photo paths by convention (`{id}/sequence.jpeg`), and the
 * app copes with a wrong guess by retrying `.png` and `.jpg` in the browser. A
 * static page cannot retry, so this map records the path that is really there.
 *
 * An exercise absent from this map renders no image. That is deliberate — a
 * missing entry is a missing object, and no image beats a broken one.
 */
export interface ExerciseMediaEntry {
  /** Path inside the `exercise-media` bucket, with the extension that exists. */
  path: string;
  /** Intrinsic pixel dimensions, so the page can reserve space and avoid layout shift. */
  width: number;
  height: number;
  /** Never empty: these images carry instructional content. */
  alt: string;
}

export const EXERCISE_MEDIA_MANIFEST: Record<string, ExerciseMediaEntry> = {
  // Empty until the script has been run somewhere with access to the bucket.
};
