/**
 * Which exercise media objects actually exist, resolved once and committed.
 *
 * GENERATED by scripts/resolve-exercise-media.ts — do not edit by hand.
 * Re-run `npm run seo:resolve-exercise-media` after uploading or replacing
 * media, and commit the diff.
 *
 * The library stores photo paths by convention (`{id}/sequence.jpeg`), and the
 * app copes with a wrong guess by retrying `.png` and `.jpg` in the browser. A
 * static page cannot retry, so this map records the path that is really there.
 *
 * An exercise absent from this map renders no image. That is deliberate — a
 * missing entry is a missing object, and no image beats a broken one.
 */
export interface ExerciseMediaEntry {
  /** Path inside the `exercise-media` bucket, with the extension that exists. */
  path: string;
  /** Intrinsic pixel dimensions, so the page can reserve space and avoid layout shift. */
  width: number;
  height: number;
  /** Never empty: these images carry instructional content. */
  alt: string;
}

export const EXERCISE_MEDIA_MANIFEST: Record<string, ExerciseMediaEntry> = {
  burpees: {
    path: 'burpees/sequence.jpeg',
    width: 2816,
    height: 1536,
    alt: 'How to do Burpees',
  },
  'air-squat': {
    path: 'air-squat/sequence.jpeg',
    width: 2816,
    height: 1536,
    alt: 'Air Squats: full squat sequence — stand, descent, ascent',
  },
  'alternating-lunges': {
    path: 'alternating-lunges/sequence.png',
    width: 1640,
    height: 959,
    alt: 'How to do Alternating Lunges',
  },
  surrenders: {
    path: 'surrenders/sequence.png',
    width: 1254,
    height: 1254,
    alt: 'How to do Surrenders',
  },
  'glute-bridges': {
    path: 'glute-bridges/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Glute Bridges',
  },
  'standard-push-ups': {
    path: 'standard-push-ups/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Standard Push-ups',
  },
  'wide-grip-push-ups': {
    path: 'wide-grip-push-ups/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Wide-Grip Push-ups',
  },
  'hand-release-push-ups': {
    path: 'hand-release-push-ups/sequence.png',
    width: 1677,
    height: 938,
    alt: 'How to do Hand-Release Push-ups',
  },
  'diamond-push-ups': {
    path: 'diamond-push-ups/sequence.png',
    width: 1672,
    height: 941,
    alt: 'How to do Diamond Push-ups',
  },
  'pike-push-ups': {
    path: 'pike-push-ups/sequence.png',
    width: 1535,
    height: 1024,
    alt: 'How to do Pike Push-ups',
  },
  'dive-bomber-push-ups': {
    path: 'dive-bomber-push-ups/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Dive-Bomber Push-ups',
  },
  't-push-ups': {
    path: 't-push-ups/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do T-Push-ups',
  },
  'plank-shoulder-taps': {
    path: 'plank-shoulder-taps/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Plank Shoulder Taps',
  },
  'commando-planks': {
    path: 'commando-planks/sequence.jpeg',
    width: 2816,
    height: 1536,
    alt: 'How to do Commando Planks',
  },
  'plank-jacks': {
    path: 'plank-jacks/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Plank Jacks',
  },
  'jump-squats': {
    path: 'jump-squats/sequence.jpeg',
    width: 2752,
    height: 1536,
    alt: 'How to do Jump Squats',
  },
  'jumping-lunges': {
    path: 'jumping-lunges/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Jumping Lunges',
  },
  'skater-jumps': {
    path: 'skater-jumps/sequence.jpeg',
    width: 2720,
    height: 1536,
    alt: 'How to do Skater Jumps',
  },
  'tuck-jumps': {
    path: 'tuck-jumps/sequence.jpeg',
    width: 2752,
    height: 1536,
    alt: 'How to do Tuck Jumps',
  },
  'broad-jumps': {
    path: 'broad-jumps/sequence.jpeg',
    width: 2406,
    height: 1760,
    alt: 'How to do Broad Jumps',
  },
  'bottom-squat-hold': {
    path: 'bottom-squat-hold/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Bottom Squat Hold',
  },
  'sphinx-push-ups': {
    path: 'sphinx-push-ups/sequence.jpeg',
    width: 2752,
    height: 1536,
    alt: 'How to do Sphinx Push-ups',
  },
  'floor-dips': {
    path: 'floor-dips/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Floor Dips',
  },
  'hollow-hold': {
    path: 'hollow-hold/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Hollow Hold',
  },
  'reverse-lunges': {
    path: 'reverse-lunges/sequence.png',
    width: 1640,
    height: 959,
    alt: 'How to do Reverse Lunges',
  },
  'single-leg-glute-bridges': {
    path: 'single-leg-glute-bridges/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Single-Leg Glute Bridges',
  },
  'standard-glute-bridges': {
    path: 'standard-glute-bridges/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Standard Glute Bridges',
  },
  'wide-push-ups': {
    path: 'wide-push-ups/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Wide Push-ups',
  },
  'side-plank-dips': {
    path: 'side-plank-dips/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Side Plank Dips',
  },
  'pogo-jumps': {
    path: 'pogo-jumps/sequence.png',
    width: 1681,
    height: 935,
    alt: 'How to do Pogo Jumps',
  },
  'fast-calf-raises': {
    path: 'fast-calf-raises/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Fast Calf Raises',
  },
  sprawls: {
    path: 'sprawls/sequence.jpeg',
    width: 2356,
    height: 1824,
    alt: 'How to do Sprawls',
  },
  'combat-sprawls': {
    path: 'combat-sprawls/sequence.jpeg',
    width: 2356,
    height: 1824,
    alt: 'How to do Combat Sprawls',
  },
  'down-ups': {
    path: 'down-ups/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Down-Ups',
  },
  'half-burpees': {
    path: 'half-burpees/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Half-Burpees',
  },
  'mountain-climbers': {
    path: 'mountain-climbers/sequence.png',
    width: 1535,
    height: 1024,
    alt: 'How to do Mountain Climbers',
  },
  'cross-body-mountain-climbers': {
    path: 'cross-body-mountain-climbers/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Cross-Body Mountain Climbers',
  },
  'high-knees': {
    path: 'high-knees/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do High Knees',
  },
  'butt-kicks': {
    path: 'butt-kicks/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Butt Kicks',
  },
  'jumping-jacks': {
    path: 'jumping-jacks/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Jumping Jacks',
  },
  'lateral-line-hops': {
    path: 'lateral-line-hops/sequence.png',
    width: 1535,
    height: 1024,
    alt: 'How to do Lateral Line Hops',
  },
  'double-tap-jumps': {
    path: 'double-tap-jumps/sequence.png',
    width: 1600,
    height: 983,
    alt: 'How to do Double-Tap Jumps',
  },
  'v-ups': {
    path: 'v-ups/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do V-Ups',
  },
  'strict-sit-ups': {
    path: 'strict-sit-ups/sequence.png',
    width: 2172,
    height: 724,
    alt: 'How to do Strict Sit-Ups',
  },
  'leg-raises': {
    path: 'leg-raises/sequence.png',
    width: 1535,
    height: 1024,
    alt: 'How to do Leg Raises',
  },
  'russian-twists': {
    path: 'russian-twists/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Russian Twists',
  },
  'bicycle-crunches': {
    path: 'bicycle-crunches/sequence.png',
    width: 1672,
    height: 941,
    alt: 'How to do Bicycle Crunches',
  },
  'plank-knee-to-elbows': {
    path: 'plank-knee-to-elbows/sequence.png',
    width: 1686,
    height: 933,
    alt: 'How to do Plank Knee-to-Elbows',
  },
  'dead-bugs': {
    path: 'dead-bugs/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Dead Bugs',
  },
  'flutter-kicks': {
    path: 'flutter-kicks/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Flutter Kicks',
  },
  'superman-raises': {
    path: 'superman-raises/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Superman Raises',
  },
  'bear-crawl-hover': {
    path: 'bear-crawl-hover/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Bear Crawl Hover',
  },
  'high-plank-hold': {
    path: 'high-plank-hold/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do High Plank Hold',
  },
  'hollow-rocks': {
    path: 'hollow-rocks/sequence.png',
    width: 2172,
    height: 724,
    alt: 'How to do Hollow Rocks',
  },
  'plank-hold': {
    path: 'plank-hold/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Plank Hold',
  },
  'plank-reaches': {
    path: 'plank-reaches/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Plank Reaches',
  },
  'side-plank-hold': {
    path: 'side-plank-hold/sequence.png',
    width: 1678,
    height: 937,
    alt: 'How to do Side Plank Hold',
  },
  'v-sit-hold': {
    path: 'v-sit-hold/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do V-Sit Hold',
  },
  'butterfly-sit-ups': {
    path: 'butterfly-sit-ups/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Butterfly Sit-ups',
  },
  'cross-body-climbers': {
    path: 'cross-body-climbers/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Cross-Body Climbers',
  },
  'bodyweight-good-mornings': {
    path: 'bodyweight-good-mornings/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Bodyweight Good Mornings',
  },
  'glute-bridge-walkouts': {
    path: 'glute-bridge-walkouts/sequence.png',
    width: 1672,
    height: 941,
    alt: 'How to do Glute Bridge Walkouts',
  },
  'reverse-snow-angels': {
    path: 'reverse-snow-angels/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Reverse Snow Angels',
  },
  'superman-hold': {
    path: 'superman-hold/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Superman Hold',
  },
  'superman-pull-downs': {
    path: 'superman-pull-downs/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Superman Pull-downs',
  },
  supermans: {
    path: 'supermans/sequence.png',
    width: 1774,
    height: 887,
    alt: 'How to do Supermans',
  },
  'bear-crawl-to-broad-jumps': {
    path: 'bear-crawl-to-broad-jumps/sequence.png',
    width: 1536,
    height: 1024,
    alt: 'How to do Bear Crawl to Broad Jumps',
  },
  'fast-air-squats': {
    path: 'fast-air-squats/sequence.jpeg',
    width: 2816,
    height: 1536,
    alt: 'How to do Fast Air Squats',
  },
  'push-ups': {
    path: 'push-ups/sequence.png',
    width: 1672,
    height: 940,
    alt: 'How to do Push-ups',
  },
  'strict-reverse-lunges': {
    path: 'strict-reverse-lunges/sequence.png',
    width: 1640,
    height: 959,
    alt: 'How to do Strict Reverse Lunges',
  },
  'walking-lunges': {
    path: 'walking-lunges/sequence.png',
    width: 1640,
    height: 959,
    alt: 'How to do Walking Lunges',
  },
};
